image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          services:
            - mysql
          name: 'Build and Test'
          script:
            - bash ./devops/build-server.sh
            - bash ./devops/build-project.sh

      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
#    - step:
#        name: 'Deployment to Staging'
#        deployment: staging
#        script:
#          - echo "Your deployment to staging script goes here..."
#    - step:
#        name: 'Deployment to Production'
#        deployment: production
#        trigger: 'manual'
#        script:
#          - echo "Your deployment to production script goes here..."


definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
